/* GarageLog v2 — Supabase integration.
   Replace the two placeholders below. NEVER use a service_role/secret key here. */
(() => {
"use strict";
const CATEGORIES=["ENGINE","SUSPENSION","BRAKES","INTERIOR","WHEELS","PAINT","BODYKIT","EXHAUST","ELECTRICAL","OTHER"];
const FALLBACK_IMAGE="https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80";
const config=window.GARAGELOG_SUPABASE||{url:"https://coiqtywzdcpremwtfrwe.supabase.co",anonKey:"sb_publishable_5whWyCwroyRSUc03OdLpvQ_kkx4r-UQ"};
const state={supabase:null,user:null,profile:null,projects:[],currentProjectId:null,currentProject:null,category:"ENGINE",editMode:true,sort:"updated",authMode:"login"};
const $=s=>document.querySelector(s),main=$("#main"),toast=$("#toast");
const configured=()=>Boolean(config.url&&!config.url.startsWith("YOUR_")&&config.anonKey&&!config.anonKey.startsWith("YOUR_"));
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();
const money=v=>new Intl.NumberFormat(undefined,{style:"currency",currency:"USD"}).format(Number(v)||0);
const dateText=v=>v?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(v)):"—";
const total=p=>(p?.parts||[]).reduce((s,x)=>s+Number(x.cost||0),0);
const logged=()=>Boolean(state.user);
function notify(m){toast.textContent=m;toast.classList.add("show");clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove("show"),2800)}
async function safe(fn,msg){try{return await fn()}catch(e){console.error(e);notify(e?.message||msg);return null}}
async function init(){
 if(configured()&&window.supabase){
  state.supabase=window.supabase.createClient(config.url,config.anonKey);
  const {data,error}=await state.supabase.auth.getSession();if(error)console.error(error);state.user=data.session?.user||null;
  state.supabase.auth.onAuthStateChange((_event,session)=>{state.user=session?.user||null;if(state.user)loadAccount().then(render);else{state.profile=null;state.projects=[];state.currentProject=null;render()}});
  if(state.user)await loadAccount();
 }else state.projects=guestProjects();
 render();
}
function guestProjects(){return[{id:"guest-demo",name:"E36 Track Refresh",description:"Temporary demo project — sign in to persist your builds.",image_url:FALLBACK_IMAGE,start_date:"2026-01-18",created_at:"2026-01-18T12:00:00Z",updated_at:"2026-08-04T16:20:00Z",parts:[{id:"gp1",category:"ENGINE",name:"Cold air intake",cost:340,install_date:"2026-02-10",source:"Example Motors",link:"",notes:"Prototype item."},{id:"gp2",category:"SUSPENSION",name:"Coilover kit",cost:1299,install_date:"2026-08-04",source:"Example Motors",link:"",notes:"Corner-weight after alignment."}],logs:[]}]}
async function loadAccount(){if(!state.user)return;await safe(async()=>{const p=await state.supabase.from("profiles").select("*").eq("id",state.user.id).maybeSingle();if(p.error)throw p.error;state.profile=p.data;await loadProjects()},"Could not load your account.")}
async function loadProjects(){const {data,error}=await state.supabase.from("project_summaries").select("*").order("updated_at",{ascending:false});if(error)throw error;state.projects=data||[]}
async function loadProject(id){
 if(!logged()){state.currentProject=state.projects.find(p=>p.id===id)||null;return state.currentProject}
 return safe(async()=>{const p=await state.supabase.from("projects").select("*").eq("id",id).single();if(p.error)throw p.error;const [parts,logs]=await Promise.all([state.supabase.from("parts").select("*").eq("project_id",id).order("created_at"),state.supabase.from("build_logs").select("*").eq("project_id",id).order("created_at",{ascending:false})]);if(parts.error)throw parts.error;if(logs.error)throw logs.error;state.currentProject={...p.data,parts:parts.data||[],logs:logs.data||[]};return state.currentProject},"Could not load this project.")}
function render(){const h=location.hash.replace(/^#\/?/,"");if(h.startsWith("project/")){state.currentProjectId=decodeURIComponent(h.split("/")[1]||"");renderBuilder()}else if(h==="projects")renderProjects();else renderHome();main.focus({preventScroll:true})}
function renderHome(){main.innerHTML=`<section class="hero"><div class="hero-inner"><p class="eyebrow">CAR PROJECT ORGANIZER</p><h1>Build the car.<br>Keep the story.</h1><p>One workspace for parts, costs, installation dates, build notes, and the decisions that turn a project car into your project car.</p><button class="button primary" data-route="projects">Take me to the editor</button><p class="muted" style="font-size:.82rem;margin-top:18px">${logged()?`Signed in as ${esc(state.profile?.username||state.user.email)}`:"Guest editor — changes disappear on refresh"}</p></div></section>`}
function renderProjects(){
 const ps=[...state.projects].sort((a,b)=>state.sort==="cost"?(b.total_cost??total(b))-(a.total_cost??total(a)):state.sort==="mods"?(b.part_count??b.parts?.length??0)-(a.part_count??a.parts?.length??0):new Date(b.updated_at||b.updatedAt)-new Date(a.updated_at||a.updatedAt));
 main.innerHTML=`<section class="page"><div class="page-header"><div><p class="eyebrow">WORKSPACE</p><h1>Your projects</h1><p class="muted">${logged()?"Persistent projects linked to your account.":"Guest mode is temporary. Sign in to persist projects."}</p></div><button class="button primary" data-action="new-project">New project</button></div>${!configured()?`<div class="warning">Supabase is not configured. Add your project URL and publishable/anon key to <code>app.js</code> after running the SQL schema.</div>`:""}<div class="toolbar"><label class="muted">Sort by <select class="select" id="sortSelect"><option value="updated">Recency</option><option value="cost">Total cost</option><option value="mods">Modification amount</option></select></label><button class="button ghost" data-action="import-prompt">Import</button><button class="button ghost" data-action="export">Export</button></div><div class="project-list">${ps.length?ps.map(projectCard).join(""):`<div class="empty"><h2>No projects yet</h2><p class="muted">Start your first build.</p></div>`}</div></section>`;
 $("#sortSelect").value=state.sort;$("#sortSelect").onchange=e=>{state.sort=e.target.value;renderProjects()}
}
function projectCard(p){return`<article class="project-card" data-open-project="${esc(p.id)}" tabindex="0" role="button"><img class="thumb" src="${esc(p.image_url||p.image||FALLBACK_IMAGE)}" alt=""><div><h3>${esc(p.name)}</h3><div class="meta">Last modified ${esc(dateText(p.updated_at||p.updatedAt))}</div><div class="project-hover">${esc(p.description||"No description yet.")}<br>${esc(dateText(p.start_date||p.startDate))} · ${p.part_count??p.parts?.length??0} modifications</div></div><div class="project-total">${money(p.total_cost??total(p))}</div></article>`}
async function renderBuilder(){
 const p=await loadProject(state.currentProjectId);if(!p){location.hash="#/projects";return}
 const parts=(p.parts||[]).filter(x=>x.category===state.category),logs=p.logs||[],visible=p.showAllLogs?logs:logs.slice(0,3);
 main.innerHTML=`<section class="page"><div class="builder-head"><img class="builder-image" src="${esc(p.image_url||FALLBACK_IMAGE)}" alt=""><div><div class="page-header" style="margin-bottom:10px"><div><p class="eyebrow">PROJECT</p><h1>${esc(p.name)}</h1></div><div class="mode-toggle"><button class="${state.editMode?"active":""}" data-action="mode" data-mode="edit">Modify</button><button class="${!state.editMode?"active":""}" data-action="mode" data-mode="view">View</button></div></div><p class="muted">${esc(p.description||"No description yet.")}</p><div class="builder-meta"><span>Builder: ${esc(state.profile?.username||"Guest")}</span><span>Start: ${esc(dateText(p.start_date))}</span><span>Modified: ${esc(dateText(p.updated_at))}</span><button class="button ghost" data-action="edit-project">Edit project</button></div></div></div>
<section class="panel"><div class="panel-head"><h2>Build Log</h2><span class="muted">${logs.length} entries</span></div>${state.editMode?`<form class="log-form" id="logForm"><textarea id="logText" placeholder="What happened? Add an install note, inspection, milestone, or setback." required maxlength="3000"></textarea><button class="button primary">Post</button></form>`:""}<div class="log-list">${visible.length?visible.map(x=>`<article class="log-item"><div class="muted">${esc(dateText(x.created_at))}</div><p>${esc(x.text)}</p></article>`).join(""):`<div class="stock">No build log entries yet.</div>`}${logs.length>3?`<button class="button ghost" data-action="logs">${p.showAllLogs?"Show less":"Show more"}</button>`:""}</div></section>
<div class="tabs">${CATEGORIES.map(c=>`<button class="tab ${state.category===c?"active":""}" data-category="${c}">${c}</button>`).join("")}</div>
<section class="panel parts-panel"><div class="panel-head"><h2>${state.category}</h2>${state.editMode?`<button class="button primary" data-action="add-part">${parts.length?"Add new parts":"Let’s change that"}</button>`:""}</div>${parts.length?`<div class="parts-list">${parts.map(partRow).join("")}</div>`:`<div class="stock">Stock</div>`}<div class="total"><span>Total project cost</span><strong>${money(total(p))}</strong></div></section></section>`;
 $("#logForm")?.addEventListener("submit",addLog)
}
function partRow(x){return`<article class="part-row" data-part="${esc(x.id)}" tabindex="0"><div><div class="part-name">${esc(x.name)}</div><div class="part-sub">${esc(x.source||"Source not specified")}</div></div><div class="cost">${money(x.cost)}</div><div class="date muted">${esc(dateText(x.install_date))}</div></article>`}
async function addLog(e){e.preventDefault();const text=$("#logText").value.trim(),p=state.currentProject;if(!text)return;if(!logged()){p.logs.unshift({id:uid(),text,created_at:new Date().toISOString()});p.updated_at=new Date().toISOString();notify("Build log posted for this guest session.");renderBuilder();return}const r=await safe(()=>state.supabase.from("build_logs").insert({project_id:p.id,text}).select().single(),"Could not save build log.");if(!r)return;await touch(p.id);notify("Build log posted.");renderBuilder()}
function openProjectDialog(p=null){$("#projectDialogTitle").textContent=p?"Edit project":"New project";$("#projectId").value=p?.id||"";$("#projectName").value=p?.name||"";$("#projectDescription").value=p?.description||"";$("#projectStartDate").value=p?.start_date||new Date().toISOString().slice(0,10);$("#projectImage").value=p?.image_url||"";$("#deleteProjectButton").hidden=!p;$("#projectDialog").showModal()}
async function saveProject(e){e.preventDefault();const id=$("#projectId").value,name=$("#projectName").value.trim();if(!name)return;const payload={name,description:$("#projectDescription").value.trim(),start_date:$("#projectStartDate").value||null,image_url:$("#projectImage").value.trim()||null};if(payload.image_url)try{new URL(payload.image_url)}catch{notify("Please enter a valid image URL.");return}
 if(!logged()){if(id){const p=state.projects.find(x=>x.id===id);Object.assign(p,payload,{updated_at:new Date().toISOString()})}else state.projects.unshift({id:uid(),...payload,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),parts:[],logs:[]});$("#projectDialog").close();notify("Guest project updated.");renderProjects();return}
 const r=await safe(async()=>{if(id){const q=await state.supabase.from("projects").update(payload).eq("id",id).select().single();if(q.error)throw q.error;return q.data}const q=await state.supabase.from("projects").insert({...payload,user_id:state.user.id}).select().single();if(q.error)throw q.error;return q.data},"Could not save project.");if(!r)return;$("#projectDialog").close();await loadProjects();notify(id?"Project updated.":"Project created.");location.hash=`#/project/${id||r.id}`}
async function deleteProject(){const id=$("#projectId").value;if(!id||!confirm("Delete this project and all of its parts/logs?"))return;if(!logged()){state.projects=state.projects.filter(x=>x.id!==id);$("#projectDialog").close();location.hash="#/projects";notify("Project deleted.");return}const r=await safe(()=>state.supabase.from("projects").delete().eq("id",id),"Could not delete project.");if(r===null)return;$("#projectDialog").close();await loadProjects();location.hash="#/projects";notify("Project deleted.")}
function openPart(x=null){$("#partDialogEyebrow").textContent=state.category;$("#partDialogTitle").textContent=x?"Part details":"Add part";$("#partId").value=x?.id||"";$("#partCategory").value=x?.category||state.category;$("#partName").value=x?.name||"";$("#partCost").value=x?.cost??"";$("#partDate").value=x?.install_date||"";$("#partSource").value=x?.source||"";$("#partLink").value=x?.link||"";$("#partNotes").value=x?.notes||"";$("#deletePartButton").hidden=!x;const disabled=!state.editMode&&!!x;$("#partForm").querySelectorAll("input:not([type=hidden]),textarea").forEach(e=>e.disabled=disabled);$("#partForm button[type=submit]").hidden=disabled;$("#partDialog").showModal()}
async function savePart(e){e.preventDefault();const p=state.currentProject,id=$("#partId").value,name=$("#partName").value.trim();if(!name)return;const payload={project_id:p.id,category:$("#partCategory").value,name,cost:Math.max(0,Number($("#partCost").value)||0),install_date:$("#partDate").value||null,source:$("#partSource").value.trim()||null,link:$("#partLink").value.trim()||null,notes:$("#partNotes").value.trim()||null};if(payload.link)try{new URL(payload.link)}catch{notify("Please enter a valid URL.");return}
 if(!logged()){if(id){const i=p.parts.findIndex(x=>x.id===id);if(i>=0)p.parts[i]={...p.parts[i],...payload}}else p.parts.push({id:uid(),...payload});p.updated_at=new Date().toISOString();$("#partDialog").close();notify(id?"Part updated.":"Part added.");renderBuilder();return}
 const r=await safe(async()=>{if(id){const q=await state.supabase.from("parts").update(payload).eq("id",id).select().single();if(q.error)throw q.error;return q.data}const q=await state.supabase.from("parts").insert(payload).select().single();if(q.error)throw q.error;return q.data},"Could not save part.");if(!r)return;await touch(p.id);$("#partDialog").close();notify(id?"Part updated.":"Part added.");renderBuilder()}
async function deletePart(){const id=$("#partId").value,p=state.currentProject;if(!id||!confirm("Delete this part?"))return;if(!logged()){p.parts=p.parts.filter(x=>x.id!==id);$("#partDialog").close();notify("Part deleted.");renderBuilder();return}const r=await safe(()=>state.supabase.from("parts").delete().eq("id",id),"Could not delete part.");if(r===null)return;await touch(p.id);$("#partDialog").close();notify("Part deleted.");renderBuilder()}
async function touch(id){const {error}=await state.supabase.from("projects").update({updated_at:new Date().toISOString()}).eq("id",id);if(error)console.error(error)}
async function authSubmit(e){e.preventDefault();$("#authError").hidden=true;if(!state.supabase){notify("Supabase is not configured.");$("#authDialog").close();return}try{const email=$("#authEmail").value.trim(),password=$("#authPassword").value,username=$("#authUsername").value.trim();let r;if(state.authMode==="login")r=await state.supabase.auth.signInWithPassword({email,password});else r=await state.supabase.auth.signUp({email,password});if(r.error)throw r.error;if(r.data.user&&state.authMode==="signup"){const q=await state.supabase.from("profiles").upsert({id:r.data.user.id,username:username||null,display_name:username||null});if(q.error)throw q.error}if(!r.data.session){notify("Account created. Check your email if confirmation is enabled.");$("#authDialog").close();return}state.user=r.data.user;await loadAccount();$("#authDialog").close();notify("Signed in.");render()}catch(e){console.error(e);$("#authError").hidden=false;$("#authError").textContent=e.message||"Authentication failed."}}
async function signOut(){const r=await safe(()=>state.supabase.auth.signOut(),"Could not sign out.");if(r===null)return;state.user=null;state.profile=null;state.projects=guestProjects();location.hash="#/projects";notify("Signed out. Guest mode is active.")}
function exportData(){const blob=new Blob([JSON.stringify({format:"GarageLog Export",version:2,exportedAt:new Date().toISOString(),projects:state.projects},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="garagelog-export.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify("Export created.")}
function importData(file){const r=new FileReader();r.onerror=()=>notify("Could not read file.");r.onload=async()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.projects))throw new Error("Invalid GarageLog export.");if(!logged()){state.projects=d.projects;notify("Import complete.");renderProjects();return}for(const p of d.projects){const q=await state.supabase.from("projects").insert({user_id:state.user.id,name:p.name||"Imported Project",description:p.description||"",image_url:p.image_url||p.image||null,start_date:p.start_date||p.startDate||null}).select().single();if(q.error)throw q.error;for(const x of p.parts||[])await state.supabase.from("parts").insert({project_id:q.data.id,category:x.category||"OTHER",name:x.name||"Imported Part",cost:Number(x.cost)||0,install_date:x.install_date||x.installDate||null,source:x.source||null,link:x.link||null,notes:x.notes||null});for(const l of p.logs||[])await state.supabase.from("build_logs").insert({project_id:q.data.id,text:l.text||""})}await loadProjects();notify("Import complete.");renderProjects()}catch(e){console.error(e);notify(e.message||"Import failed.")}};r.readAsText(file)}
document.addEventListener("click",e=>{const route=e.target.closest("[data-route]");if(route){location.hash="#/"+route.dataset.route;return}const op=e.target.closest("[data-open-project]");if(op){location.hash="#/project/"+encodeURIComponent(op.dataset.openProject);return}const cat=e.target.closest("[data-category]");if(cat){state.category=cat.dataset.category;renderBuilder();return}const part=e.target.closest("[data-part]");if(part){const x=state.currentProject?.parts?.find(p=>p.id===part.dataset.part);if(x)openPart(x);return}const a=e.target.closest("[data-action]");if(!a)return;switch(a.dataset.action){case"new-project":openProjectDialog();break;case"edit-project":openProjectDialog(state.currentProject);break;case"export":exportData();break;case"import-prompt":$("#importInput").click();break;case"auth":if(state.user)document.querySelector(".account-menu")?.remove()||showAccountMenu();else $("#authDialog").showModal();break;case"mode":state.editMode=a.dataset.mode==="edit";renderBuilder();break;case"add-part":openPart();break;case"logs":state.currentProject.showAllLogs=!state.currentProject.showAllLogs;renderBuilder();break;case"signout":signOut();break}});
function showAccountMenu(){const m=document.createElement("div");m.className="account-menu";m.innerHTML=`<div class="muted" style="padding:7px 10px">${esc(state.profile?.username||state.user.email)}</div><button data-action="signout">Sign out</button>`;document.body.appendChild(m)}
$("#projectForm").addEventListener("submit",saveProject);$("#deleteProjectButton").addEventListener("click",deleteProject);$("#partForm").addEventListener("submit",savePart);$("#deletePartButton").addEventListener("click",deletePart);$("#authForm").addEventListener("submit",authSubmit);
$("#toggleAuth").addEventListener("click",()=>{state.authMode=state.authMode==="login"?"signup":"login";const s=state.authMode==="signup";$("#authTitle").textContent=s?"Create account":"Sign in";$("#authSubmit").textContent=s?"Create account":"Sign in";$("#toggleAuth").textContent=s?"Back to sign in":"Create account";$("#usernameWrap").hidden=!s});
$("#importInput").addEventListener("change",e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=""});window.addEventListener("hashchange",render);init();
})();